name: Trigger auto deployment for e2t1m0t0r-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/e2t1m0t0r-backend-AutoDeployTrigger-90f5b44a-4ac3-4f02-9ba6-371bf1bf4bda.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.E2T1M0T0RBACKEND_REGISTRY_USERNAME }}
          password: ${{ secrets.E2T1M0T0RBACKEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kubakra/e2t1m0t0r-backend:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.E2T1M0T0RBACKEND_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n e2t1m0t0r-backend -g e2t1m0t0r --server docker.io --username  ${{ secrets.E2T1M0T0RBACKEND_REGISTRY_USERNAME }} --password ${{ secrets.E2T1M0T0RBACKEND_REGISTRY_PASSWORD }}
            az containerapp update -n e2t1m0t0r-backend -g e2t1m0t0r --image kubakra/e2t1m0t0r-backend:${{ github.sha }}
